ALTER TABLE COMMUNITY
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_COMMUNITY;

/* 커뮤니티 */
DROP TABLE COMMUNITY 
	CASCADE CONSTRAINTS;

/* 커뮤니티 */
CREATE TABLE COMMUNITY (
	CT_IDX NUMBER(8) NOT NULL, /* 커뮤니티번호 */
	CT_TITLE VARCHAR2(50) NOT NULL, /* 커뮤니티제목 */
	CT_WRITER VARCHAR2(50) NOT NULL, /* 커뮤니티작성자 */
	CT_CONTENT VARCHAR2(500), /* 커뮤니티내용 */
	CT_READNUM NUMBER(12) NOT NULL, /* 커뮤니티조회수 */
	CT_DATE DATE NOT NULL /* 커뮤니티등록일 */
);

COMMENT ON TABLE COMMUNITY IS '커뮤니티';

COMMENT ON COLUMN COMMUNITY.CT_IDX IS '커뮤니티번호';

COMMENT ON COLUMN COMMUNITY.CT_TITLE IS '커뮤니티제목';

COMMENT ON COLUMN COMMUNITY.CT_WRITER IS '커뮤니티작성자';

COMMENT ON COLUMN COMMUNITY.CT_CONTENT IS '커뮤니티내용';

COMMENT ON COLUMN COMMUNITY.CT_READNUM IS '커뮤니티조회수';

COMMENT ON COLUMN COMMUNITY.CT_DATE IS '커뮤니티등록일';

CREATE UNIQUE INDEX PK_COMMUNITY
	ON COMMUNITY (
		CT_IDX ASC
	);

ALTER TABLE COMMUNITY
	ADD
		CONSTRAINT PK_COMMUNITY
		PRIMARY KEY (
			CT_IDX
		);