ALTER TABLE M_REVIEW
	DROP
		CONSTRAINT FK_MEMBER_TO_M_REVIEW
		CASCADE;

ALTER TABLE M_REVIEW
	DROP
		CONSTRAINT FK_MUSIC_TO_M_REVIEW
		CASCADE;

ALTER TABLE M_REVIEW
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_M_REVIEW;

/* À½¿ø´ñ±Û */
DROP TABLE M_REVIEW 
	CASCADE CONSTRAINTS;

/* À½¿ø´ñ±Û */
CREATE TABLE M_REVIEW (
	MR_IDX NUMBER(8) NOT NULL, /* À½¿ø´ñ±Û¹øÈ£ */
	MR_CONTENT VARCHAR2(500) NOT NULL, /* ´ñ±Û³»¿ë */
	MR_DATE DATE NOT NULL, /* ´ñ±Ûµî·ÏÀÏ */
	IDX_FK NUMBER(8) NOT NULL, /* È¸¿ø¹øÈ£ */
	MIDX NUMBER(8) NOT NULL /* À½¿ø¹øÈ£ */
);

COMMENT ON TABLE M_REVIEW IS 'À½¿ø´ñ±Û';

COMMENT ON COLUMN M_REVIEW.MR_IDX IS 'À½¿ø´ñ±Û¹øÈ£';

COMMENT ON COLUMN M_REVIEW.MR_CONTENT IS '´ñ±Û³»¿ë';

COMMENT ON COLUMN M_REVIEW.MR_DATE IS '´ñ±Ûµî·ÏÀÏ';

COMMENT ON COLUMN M_REVIEW.IDX_FK IS 'È¸¿ø¹øÈ£';

COMMENT ON COLUMN M_REVIEW.MIDX IS 'À½¿ø¹øÈ£';

CREATE UNIQUE INDEX PK_M_REVIEW
	ON M_REVIEW (
		MR_IDX ASC
	);

ALTER TABLE M_REVIEW
	ADD
		CONSTRAINT PK_M_REVIEW
		PRIMARY KEY (
			MR_IDX
		);

ALTER TABLE M_REVIEW
	ADD
		CONSTRAINT FK_MEMBER_TO_M_REVIEW
		FOREIGN KEY (
			IDX_FK
		)
		REFERENCES MEMBER (
			IDX
		);

ALTER TABLE M_REVIEW
	ADD
		CONSTRAINT FK_MUSIC_TO_M_REVIEW
		FOREIGN KEY (
			MIDX
		)
		REFERENCES MUSIC (
			MIDX
		);

create sequence M_REVIEW_SEQ
increment by 1
start with 1
nocache;

commit;