ALTER TABLE MPM_MEMBER
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_MEMBER;

/* 회원 */
DROP TABLE MPM_MEMBER 
	CASCADE CONSTRAINTS;

/* 회원 */
CREATE TABLE MPM_MEMBER (
	IDX NUMBER(8) NOT NULL, /* 회원번호 */
	NICKNAME VARCHAR2(30) NOT NULL, /* 회원이름 */
	USERID VARCHAR2(50) NOT NULL, /* 아이디 */
	EMAIL VARCHAR2(100), /* 이메일 */
	PWD VARCHAR2(30) NOT NULL /* 비밀번호 */
);

COMMENT ON TABLE MPM_MEMBER IS '회원';

COMMENT ON COLUMN MPM_MEMBER.IDX IS '회원번호';

COMMENT ON COLUMN MPM_MEMBER.NICKNAME IS '회원이름';

COMMENT ON COLUMN MPM_MEMBER.USERID IS '아이디';

COMMENT ON COLUMN MPM_MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN MPM_MEMBER.PWD IS '비밀번호';

CREATE UNIQUE INDEX PK_MEMBER
	ON MPM_MEMBER (
		IDX ASC
	);

ALTER TABLE MPM_MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			IDX
		);