ALTER TABLE REVIEW
	DROP
		CONSTRAINT FK_MEMBER_TO_REVIEW
		CASCADE;

ALTER TABLE REVIEW
	DROP
		CONSTRAINT FK_COMMUNITY_TO_REVIEW
		CASCADE;

ALTER TABLE REVIEW
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_REVIEW;

/* ´ñ±Û */
DROP TABLE REVIEW 
	CASCADE CONSTRAINTS;

/* ´ñ±Û */
CREATE TABLE REVIEW (
	RE_IDX NUMBER(8) NOT NULL, /* ´ñ±Û¹øÈ£ */
	RE_WRITER VARCHAR2(50) NOT NULL, /* ´ñ±ÛÀÛ¼ºÀÚ */
	RE_CONTENT VARCHAR2(500) NOT NULL, /* ´ñ±Û³»¿ë */
	RE_DATE DATE NOT NULL, /* ´ñ±Ûµî·ÏÀÏ */
	IDX_FK NUMBER(8), /* È¸¿ø¹øÈ£ */
	CT_IDX NUMBER(8) /* Ä¿¹Â´ÏÆ¼¹øÈ£ */
);

COMMENT ON TABLE REVIEW IS '´ñ±Û';

COMMENT ON COLUMN REVIEW.RE_IDX IS '´ñ±Û¹øÈ£';

COMMENT ON COLUMN REVIEW.RE_WRITER IS '´ñ±ÛÀÛ¼ºÀÚ';

COMMENT ON COLUMN REVIEW.RE_CONTENT IS '´ñ±Û³»¿ë';

COMMENT ON COLUMN REVIEW.RE_DATE IS '´ñ±Ûµî·ÏÀÏ';

COMMENT ON COLUMN REVIEW.IDX_FK IS 'È¸¿ø¹øÈ£';

COMMENT ON COLUMN REVIEW.CT_IDX IS 'Ä¿¹Â´ÏÆ¼¹øÈ£';

CREATE UNIQUE INDEX PK_REVIEW
	ON REVIEW (
		RE_IDX ASC
	);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT PK_REVIEW
		PRIMARY KEY (
			RE_IDX
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_MEMBER_TO_REVIEW
		FOREIGN KEY (
			IDX_FK
		)
		REFERENCES MEMBER (
			IDX
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_COMMUNITY_TO_REVIEW
		FOREIGN KEY (
			CT_IDX
		)
		REFERENCES COMMUNITY (
			CT_IDX
		);